Edangelion/detect hasmany
wantedly/pq2gorm pull request #15
Opened 2016-09-26 11:45 UTC by edangelion

## WHY
For adding function of inferring hasmany relations.

## WHAT
Add function "AddHasMany".
Add testdata.

2016-09-26 12:27 UTC, dtan4 commented on testdata/models/post_comment.go
> -	Post      *Post      `json:"post"` // This line is infered from column name "post_id".
Why is this removed?

2016-09-26 12:27 UTC, dtan4 commented on testdata/models/project.go
> -	Company     *Company `json:"company"` // This line is infered from column name "company_id".
Why is this removed?

2016-09-26 12:28 UTC, dtan4 commented
Please create `testdata/models/user.go` to compare the result of user model.

2016-09-26 12:29 UTC, dtan4 requested changes

2016-09-26 14:14 UTC, edangelion commented on testdata/models/post_comment.go
> -	Post      *Post      `json:"post"` // This line is infered from column name "post_id".
I have changed inferORM function to infer only when the column name existed in tables. 
I think this will improve inference accuracy

2016-09-27 01:26 UTC, dtan4 commented on testdata/models/post_comment.go
> -	Post      *Post      `json:"post"` // This line is infered from column name "post_id".
OK, I see.

2016-09-27 01:42 UTC, dtan4 requested changes

2016-09-27 01:42 UTC, dtan4 commented on main.go
> +	paramsS := []*TemplateParams{}
What is the meaning of `paramsS` ? Please reconsider this variable name.

2016-09-27 01:42 UTC, dtan4 commented on generate.go
> +			hasMany[gormColumnName(infColName)] = append(hasMany[gormColumnName(infColName)], table)
`gormColumnName(infColName)` is called 4 times.
How about define temporary variable to store `gormColumnName(infColName)`?

2016-09-27 01:42 UTC, dtan4 commented on main.go
> +		SaveModel(table, paramsS[i], dir)
Please catch and handle error by `SaveModel`.

2016-09-27 01:55 UTC, edangelion commented on main.go
> +	paramsS := []*TemplateParams{}
I have changed pamasS to modelParams.

2016-09-27 01:57 UTC, edangelion commented
Thank you.
I have changed codes .

2016-09-27 02:24 UTC, dtan4 requested changes

2016-09-27 02:24 UTC, dtan4 commented on main.go
> +	for i, table := range tables {
How about using `map[string]*TemplateParams` for `modelParams`?

This loop can be written like below:

```go
	for table, param := range modelParams {
		fmt.Println("Add relation for Table name: " + table)

		AddHasMany(param)

		if err := SaveModel(table, param, dir); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
	}
```

2016-09-27 02:40 UTC, edangelion commented on main.go
> +	for i, table := range tables {
Thank you. I have changed modelParams to use map.

2016-09-27 05:46 UTC, dtan4 commented
LGTM 👍 Thanks ❗

2016-09-27 05:46 UTC, dtan4 approved these changes

2016-09-27 05:46 UTC, merged